apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mantle-node.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mantle-node.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt_secret_txt: {{ include "mantle-node.jwtSecret" . | quote }}
  p2p_node_key_txt: {{ include "mantle-node.p2pNodeKey" . | quote }}
