# Mantle Network L2 history Geth Node Docker Compose Configuration
# This configuration file is used to deploy a Mantle Network L2 Geth node
# Main Features:
# 1. Run L2 Geth node and connect to Mantle Network mainnet
# 2. Configure health check to ensure node operation
# 3. Set up data persistence storage
# 4. Configure RPC interface access
#
# Usage Instructions:
# 1. Ensure Docker and Docker Compose are installed
# 2. download history snapshot 
# 3. Run command: docker-compose -f docker-compose-mainnetv1.yml up -d
#
# Important Notes:
# - must download history snapshot , do not use snapshot of v2
# - Ensure sufficient disk space for data storage
# - Regular backup of data directory is recommended


version: '3.4'

x-healthcheck: &healthcheck
  test: [ "CMD", "curl", "-sf", "http://localhost:18545" ]
  interval: 5s
  timeout: 5s
  retries: 3
  start_period: 30s

services:
  replica:
    image: mantlenetworkio/l2geth:v0.4.3
    entrypoint: sh ./geth.sh
    env_file:
      - ./mainnet/envs/geth.env #
    volumes:
      - ./data/gethv1:/root/.ethereum/geth/
    environment:
      ETH1_HTTP: $L1_RPC_MAINNET #change this 
      SEQUENCER_CLIENT_HTTP: https://rpc.mantle.xyz
      ROLLUP_STATE_DUMP_PATH: https://mantlenetworkio.github.io/networks/mainnet/genesis.json
      ROLLUP_BACKEND: 'l2'
      ETH1_CTC_DEPLOYMENT_HEIGHT: 8
      RETRIES: 60
      ROLLUP_VERIFIER_ENABLE: 'true'
    ports:
      - ${VERIFIER_HTTP_PORT:-18545}:18545
      - ${VERIFIER_WS_PORT:-18546}:18546